package oracle.users;



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import oracle.function.Exam;
import oracle.function.Exam1;
import oracle.function.ExamReport;
import oracle.function.Question;
import oracle.function.UserInfo;
        
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mehuli
 */
public class ConductExamFrame extends javax.swing.JFrame {

    Exam exam;
    int time;
    int count;
    int index=0;
    Timer timer;
    ArrayList<Question> paper;
    String[] answers;
    public ConductExamFrame(Exam exam) {
        initComponents();
       // lblIcon.setIcon(new ImageIcon(getClass().getResource("copy.gif")));
        this.exam = exam;
        time = exam.getDuration()*60;
        count = exam.getNumberOfQuestions();
        answers = new String[count];
        timer = new Timer(1000,new ActionListener()
        {
            public void actionPerformed(ActionEvent evt){
                time--;
                setTimeRemaining();
                if(time==0){
                    timer.stop();
                    JOptionPane.showMessageDialog(ConductExamFrame.this, "Time Over\nExam will now close");
                    finishExam();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblCounter = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        rbOptionA = new javax.swing.JRadioButton();
        rbOptionB = new javax.swing.JRadioButton();
        rbOptionC = new javax.swing.JRadioButton();
        rbOptionD = new javax.swing.JRadioButton();
        btnFinish = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblQuestions = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 204));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPrevious.setForeground(new java.awt.Color(102, 102, 102));
        btnPrevious.setText("Previous");
        btnPrevious.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnPrevious.setContentAreaFilled(false);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setForeground(new java.awt.Color(102, 102, 102));
        btnNext.setText("Next");
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnNext.setContentAreaFilled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblCounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCounter.setForeground(new java.awt.Color(102, 102, 102));
        lblCounter.setText("Q.1. ");

        lblQuestion.setForeground(new java.awt.Color(51, 51, 51));
        lblQuestion.setText("jLabel1");

        options.add(rbOptionA);
        rbOptionA.setForeground(new java.awt.Color(51, 51, 51));
        rbOptionA.setText("jRadioButton1");

        options.add(rbOptionB);
        rbOptionB.setForeground(new java.awt.Color(51, 51, 51));
        rbOptionB.setText("jRadioButton1");

        options.add(rbOptionC);
        rbOptionC.setForeground(new java.awt.Color(51, 51, 51));
        rbOptionC.setText("jRadioButton1");

        options.add(rbOptionD);
        rbOptionD.setForeground(new java.awt.Color(51, 51, 51));
        rbOptionD.setText("jRadioButton1");

        btnFinish.setForeground(new java.awt.Color(102, 102, 102));
        btnFinish.setText("Finish");
        btnFinish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnFinish.setContentAreaFilled(false);
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCounter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQuestion))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(rbOptionB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbOptionD))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(rbOptionA)
                            .addGap(60, 60, 60)
                            .addComponent(rbOptionC))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCounter)
                    .addComponent(lblQuestion))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOptionA)
                    .addComponent(rbOptionC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOptionB)
                    .addComponent(rbOptionD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblQuestions.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblQuestions.setForeground(new java.awt.Color(102, 102, 102));
        lblQuestions.setText("Questions : ");

        lblSubject.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(102, 102, 102));
        lblSubject.setText("Subject : ");

        lblTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(102, 102, 102));
        lblTime.setText("Time Remaining : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuestions)
                        .addGap(180, 180, 180))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(lblQuestions))
                .addGap(15, 15, 15)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        saveAnswer();
        index++;
        setQuestion();
    }//GEN-LAST:event_btnNextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblSubject.setText("Subject : "+exam.getExamName());
        lblQuestions.setText("Questions : "+exam.getNumberOfQuestions());
        
        paper = DBManager.generateQuestionPaper(exam);
        setQuestion();
        
        setTimeRemaining();
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        saveAnswer();
        index--;
        setQuestion();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Are Your Sure","Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            timer.stop();
            finishExam();
        }
            
    }//GEN-LAST:event_btnFinishActionPerformed
    private void setTimeRemaining(){
        int min = time/60;
        int sec = time%60;
        lblTime.setText("Time Remaining : "+min+":"+sec+" Minutes");
    }
    private void finishExam(){
        saveAnswer();
        ExamReport report = new ExamReport();
        String userId = System.getProperty("userId");
        UserInfo info = DBManager.getUserInfo(userId);
        
        report.setUserName(info.getName());
        report.setExamName(exam.getExamName());
        report.setTotalQuestions(exam.getNumberOfQuestions());
        report.setAttempted(getAttempted());
        report.setCorrect(getCorrect());
        double score = ((double)report.getCorrect()/report.getTotalQuestions())*100;
        report.setScore(score);
        DBManager.saveReport(report);
        ReportFrame f = new ReportFrame(report);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        this.dispose();
    }
    private int getAttempted(){
        int count=0;
       for(int i=0;i<answers.length;i++){
           if(answers[i] != null)
               count++;
       } 
       return count;
    }
    private int getCorrect(){
        int count=0;
        for(int i=0;i<answers.length;i++){
            if(answers[i]==null)
                continue;
            Question q = paper.get(i);
            if(answers[i].equals(q.getAnswer())){
                count++;
            }
        }
        return count;
    }
    private void setQuestion(){
        options.clearSelection();
        Question q = paper.get(index);
        lblCounter.setText("Q."+(index+1)+".");
        lblQuestion.setText(q.getQuestion());
        rbOptionA.setText(q.getOptionA());
        rbOptionB.setText(q.getOptionB());
        rbOptionC.setText(q.getOptionC());
        rbOptionD.setText(q.getOptionD());
        if(index==0){
            btnPrevious.setEnabled(false);
        }else{
            btnPrevious.setEnabled(true);
        }
        
        if(index==count-1){
            btnNext.setEnabled(false);
        }else{
            btnNext.setEnabled(true);
        }
        setAnswer();
    }
    private void setAnswer(){
        String ans=null;
        if(answers[index]==null)
            return;
        if(answers[index].equals("A")) rbOptionA.setSelected(true);
        if(answers[index].equals("B")) rbOptionB.setSelected(true);
        if(answers[index].equals("C")) rbOptionC.setSelected(true);
        if(answers[index].equals("D")) rbOptionD.setSelected(true);
    }
    private void saveAnswer(){
        String ans=null;
        if(rbOptionA.isSelected()) ans="A";
        else if(rbOptionB.isSelected()) ans="B";
        else if(rbOptionC.isSelected()) ans="C";
        else if(rbOptionD.isSelected()) ans="D";
        answers[index] = ans;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuestions;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTime;
    private javax.swing.ButtonGroup options;
    private javax.swing.JRadioButton rbOptionA;
    private javax.swing.JRadioButton rbOptionB;
    private javax.swing.JRadioButton rbOptionC;
    private javax.swing.JRadioButton rbOptionD;
    // End of variables declaration//GEN-END:variables
}
