package oracle.users;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportFrame.java
 *
 * Created on May 14, 2011, 5:47:27 PM
 */


import oracle.function.ExamReport;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Nagendra
 */
public class ReportFrame extends javax.swing.JFrame{

    private ExamReport report;

    /** Creates new form ReportFrame */
    public ReportFrame(ExamReport report) {
        initComponents();
        this.report = report;
        lblStudentName.setText(report.getUserName());
        lblExamDate.setText(getDate());
        lblSubject.setText(report.getExamName());
        lblNumberOfQuestions.setText("" + report.getTotalQuestions());
        lblAttempted.setText("" + report.getAttempted());
        lblCorrect.setText("" + report.getCorrect());
        lblScore.setText("" + report.getScore() + "%");
        if(report.getScore()>=50){
            lblResult.setText("Passed");
            lblResult.setForeground(Color.green);
        }else{
            lblResult.setText("Failed");
            lblResult.setForeground(Color.red);
        }
    }
    
    private String getDate(){
        Date d = new Date();
        SimpleDateFormat fmt = new SimpleDateFormat("dd-MMMM-yyyy");
        String str = fmt.format(d);
        return str;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblAttempted = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblExamDate = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumberOfQuestions = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 204)), "Exam Result", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Black", 0, 36), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Attempted : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 185, -1, -1));

        lblAttempted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAttempted.setForeground(new java.awt.Color(51, 51, 51));
        lblAttempted.setText("jLabel13");
        jPanel1.add(lblAttempted, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 185, 180, -1));

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblScore.setForeground(new java.awt.Color(51, 51, 51));
        lblScore.setText("jLabel15");
        lblScore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 237, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Score : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 238, -1, -1));

        lblCorrect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(51, 51, 51));
        lblCorrect.setText("jLabel14");
        jPanel1.add(lblCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 211, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Student Name : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 67, -1, -1));

        lblExamDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblExamDate.setForeground(new java.awt.Color(102, 102, 102));
        lblExamDate.setText("jLabel10");
        jPanel1.add(lblExamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 119, 320, -1));

        lblSubject.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(102, 102, 102));
        lblSubject.setText("jLabel11");
        jPanel1.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 93, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Subject : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 93, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Correct : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 211, -1, -1));

        lblNumberOfQuestions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumberOfQuestions.setForeground(new java.awt.Color(51, 51, 51));
        lblNumberOfQuestions.setText("jLabel12");
        jPanel1.add(lblNumberOfQuestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 159, 180, -1));

        lblStudentName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(102, 102, 102));
        lblStudentName.setText("jLabel9");
        jPanel1.add(lblStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 67, 247, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Result : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 266, -1, -1));

        btnClose.setForeground(new java.awt.Color(102, 102, 102));
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 102, 32));

        lblResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(51, 51, 51));
        lblResult.setText("jLabel15");
        lblResult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 265, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Date : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Number of Questions : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 159, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/oraclewr (4x4).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Where Words Illuminate Wisdom");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAttempted;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblExamDate;
    private javax.swing.JLabel lblNumberOfQuestions;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblSubject;
    // End of variables declaration//GEN-END:variables
}
